In [ ]:
text='HELLO this is a sample email o check bunny and ram'
text_lower=text.lower()
print(text_lower)

hello this is a sample email o check bunny and ram


In [ ]:
import re
text='HELLO this is a sample email to check bunny or rohit'
text_clean=re.sub(r'[a-z]','05',text)
print(text_clean)

HELLO 05050505 0505 05 050505050505 0505050505 0505 0505050505 0505050505 0505 0505050505


In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords', quiet=True)
stop_words=set(stopwords.words('english'))
text='hello this is sample of my age and good decision and maintance the age formate of the data '
token=[]

for word in text.split():
  if word not in stop_words:
    token.append(word)
print(token)

['hello', 'sample', 'age', 'good', 'decision', 'maintance', 'age', 'formate', 'data']


In [ ]:
import nltk
nltk.download('wordnet',quiet=True)
nltk.download('punkt_tab', quiet=True)
sentence='i dont love spam email ls do you'
basics=sentence.split()
from nltk.tokenize import word_tokenize
smart=word_tokenize(sentence.lower())
print('nltk tokenise',smart)

nltk tokenise ['i', 'dont', 'love', 'spam', 'email', 'ls', 'do', 'you']


In [ ]:
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download('wordnet', quiet=True)

stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

words = ['running', 'studies', 'better', 'caring', 'happily']

for word in words:
    stem = stemmer.stem(word)
    lemma = lemmatizer.lemmatize(word, pos='v')

    print(f'{word:12} | stem: {stem:10} | lemma: {lemma}')

running      | stem: run        | lemma: run
studies      | stem: studi      | lemma: study
better       | stem: better     | lemma: better
caring       | stem: care       | lemma: care
happily      | stem: happili    | lemma: happily


In [2]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download(['stopwords','wordnet','punkt'],quiet=True)
stop_words=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

def preprocess(text):
  text=text.lower()
  text=re.sub(r'[^a-zA-Z]',' ',text)
  tokens =text.split()
  filtered_tokens=[]
  for w in tokens:
    if w not in stop_words:
      filtered_tokens.append(w)

    lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens]

  return ' '.join(lemmatized_tokens)
sample_text = 'i am going to running the some one story'
processed_text = preprocess(sample_text)
print(f"Original: {sample_text}\nProcessed: {processed_text}")

Original: i am going to running the some one story
Processed: going running one story


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
emails=[
    'cricket match cricket match cricket',
    'free win money free win money',
    'cricket match free win money cricket',
]
cv=CountVectorizer()
x=cv.fit_transform(emails).toarray()
print('vocabulary:',cv.get_feature_names_out())
print('row matrix:')
print(x)

vocabulary: ['cricket' 'free' 'match' 'money' 'win']
row matrix:
[[3 0 2 0 0]
 [0 2 0 2 2]
 [2 1 1 1 1]]


In [7]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
emails=[
    'cricket match cricket match cricket',
    'free win money free win money',
    'cricket match free win money cricket',
]
tfidf=TfidfVectorizer(sublinear_tf=True)
x=tfidf.fit_transform(emails).toarray()
print('feature:',tfidf.get_feature_names_out())
print('if-idf metrix(rounded):')

import numpy as np
print(np.round(x,3))

feature: ['cricket' 'free' 'match' 'money' 'win']
if-idf metrix(rounded):
[[0.778 0.    0.628 0.    0.   ]
 [0.    0.577 0.    0.577 0.577]
 [0.646 0.382 0.382 0.382 0.382]]
